name: PerfectModeration
version: '1.0-SNAPSHOT'
main: org.mc.perfectmoderation.PerfectModeration
api-version: '1.20'
load: STARTUP

commands:
  report:

  reports:

  temp-mute:

  unmute:

  temp-ban:

  unban:

  warn:
